### ISSUE TITLE
RScript: %in% can't be parsed

### ISSUE THREAD

**Issue by ghost** [CampagneLaboratory/MetaR#20]
Expected behavior: Create new concept `Match`

**Comment by fac2003** [comment]
This looks like a custom user operator that could be handled the same way as the magritte and dplyr operator.  Could you provide an example and reference for which package defines this operator?

**Comment by ghost** [comment]
It is an alternative binary operator for the [match function](https://stat.ethz.ch/R-manual/R-devel/library/base/html/match.html) in the standard packages.

**Comment by fac2003** [comment]
Now implemented in master.
