### ISSUE TITLE
All arguments to rename must be named. (when joining tables)

### ISSUE THREAD

**Issue by fac2003** [CampagneLaboratory/MetaR#6]
This is a known issue when dplyr is loaded instead of plyr. See http://stackoverflow.com/questions/30562819/error-message-when-running-simple-rename-function-in-r

In MetaR, dplyr is required by some statements (e.g., UpSet statement in the plots language). We know that we cannot remove the quotes around column names because some column names are not valid identifiers in R (e.g., element-id is a case in point). 
We therefore need to make sure we call the correct function in the plyr package. The following works:

T <- plyr::rename(T, c(genes="element-id"))

**Comment by cookatrice** [comment]
thanks. :)
